### ISSUE TITLE
paycheck3 not allowing me to play heists

### ISSUE THREAD

**Issue by Kyle30894** [SlejmUr/PayCheck3#33]
unable to play heists with paycheck3 included images shows steam running with paycheck 3 and pd3

![image](https://github.com/SlejmUr/PayCheck3/assets/156033486/9e8ba136-6e5b-403b-b2a0-0601780283a5)

**Comment by SlejmUr** [comment]
Because that is a Matchmaking screen, Matchmaking is not supported. Old mod (OHSM) would worked but because some guys running with under live server and they could hosted DLC Heists without owning it. (They got temporary blocked/banned/kicked)

Need to edit much more to re enable old heists section and need to check each user owns the game, dlc or not.

But because I waiting for SBZ to drop their QoL update that will probably going to release in February so most of stuff postponed to after update (and because they added all heist to one .pak that made me question why I doing this)

**Comment by Kyle30894** [comment]
> Because that is a Matchmaking screen, Matchmaking is not supported. Old mod (OHSM) would worked but because some guys running with under live server and they could hosted DLC Heists without owning it. (They got temporary blocked/banned/kicked)
> 
> Need to edit much more to re enable old heists section and need to check each user owns the game, dlc or not.
> 
> But because I waiting for SBZ to drop their QoL update that will probably going to release in February so most of stuff postponed to after update (and because they added all heist to one .pak that made me question why I doing this)

ahhh okay gotcha thanks for the reply :)

**Comment by Kyle30894** [comment]
also how would i import my save file?

**Comment by SlejmUr** [comment]
You can't rn but will gonna make an app. (Will gonna test with steam currently because that one is easier [and you also own it on steam too])

**Comment by Kyle30894** [comment]
> You can't rn but will gonna make an app. (Will gonna test with steam currently because that one is easier [and you also own it on steam too])

if you need any testers hit me up i'll be happy to lend a hand or 2

**Comment by SlejmUr** [comment]
Updated, now you can get your live save. (rename files, edit userId and you good to go & use it)
